server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  # Selalu ambil versi terbaru saat mengembangkan.
  add_header Cache-Control "no-store" always;

  location / {
    try_files $uri /index.html;
  }
}
